name: hatarakujikan_web
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  modal_bottom_sheet: ^2.0.0
  provider: ^5.0.0
  flutter_spinkit: ^5.0.0
  shared_preferences: ^2.0.5
  month_picker_dialog: ^0.4.0
  common_utils: ^2.0.2
  qr_flutter: ^4.0.0
  flutter_admin_scaffold: ^1.0.0
  data_table_2: ^2.0.3
  table_calendar: ^3.0.2
  csv: ^5.0.0
  pdf: ^3.4.2
  universal_html: ^2.0.8
  multiple_stream_builder: ^2.0.0
  google_maps_flutter: ^2.0.6
  google_maps_flutter_web: ^0.3.0+2
  http: ^0.13.3
  intl: ^0.16.1
dependency_overrides:
  intl: ^0.17.0-nullsafety.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.otf
